services:
  - type: web
    name: homeverse-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python simple_backend.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: homeverse-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: USE_POSTGRESQL
        value: "true"
      - key: CORS_ORIGINS
        value: "*"
      - key: SENDGRID_API_KEY
        sync: false

databases:
  - name: homeverse-db
    plan: starter
    databaseName: homeverse_db
    user: homeverse_user
