services:
  # Backend API service
  - type: web
    name: homeverse-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_backend.py
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: homeverse-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: homeverse-redis
          type: redis
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: UNSTRUCTURED_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: COMPANY_KEY
        value: "default-company-key"

  # Frontend Next.js service
  - type: web
    name: homeverse-frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://homeverse-api.onrender.com
      - key: NEXT_PUBLIC_MAPBOX_TOKEN
        sync: false

  # Redis service
  - type: redis
    name: homeverse-redis
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

databases:
  - name: homeverse-db
    databaseName: homeverse
    user: homeverse
    postgresMajorVersion: 15