services:
  - type: web
    name: homeverse-api
    runtime: python
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements_minimal_supabase.txt"
    startCommand: "python supabase_backend.py"
    region: oregon
    plan: starter
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: SENDGRID_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONPATH
        value: "."

# No database needed - using Supabase!
