# Fly.io deployment configuration

app = "homeverse-api"
primary_region = "ord"

[build]
  dockerfile = "docker/Dockerfile"

[env]
  PORT = "8000"
  LOG_LEVEL = "INFO"
  SQL_DEBUG = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
  worker = "celery -A app.workers.celery_app worker --loglevel=info"
  beat = "celery -A app.workers.celery_app beat --loglevel=info"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"

[deploy]
  release_command = "alembic upgrade head"

# Secrets (set via `fly secrets set`)
# DATABASE_URL
# REDIS_URL  
# JWT_SECRET_KEY
# OPENAI_API_KEY
# SENDGRID_API_KEY
# SUPABASE_URL
# SUPABASE_ANON_KEY